version: '3.8'
services:
    db:
        image: postgres:15-alpine
        restart: always

        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data

    backend:
        build: ./backend
        ports:
            - '8000:8000'
        depends_on:
            - db

    frontend:
        build: ./frontend
        ports:
            - 8080:80
        depends_on:
            - backend

volumes:
    db-data:
