version: '3.8'

services:
    db:
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data

    backend:
        build: ./backend
        command: yarn start
        ports:
            - "8001:8000"
        depends_on:
            - db
    
volumes:
    db-data:
